apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agenda-ui
  template:
    metadata:
      labels:
        app: agenda-ui
    spec:
      containers:
        - name: agenda-ui
          image: docker.io/rsantiag085/agenda-ui:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80